version: '3'

networks:
  backend:
    driver: bridge
services:
### NGINX Server #########################################
    nginx:
      container_name: nginx
      build:
        context: ./nginx
      volumes:
        - ./data/nginx/log:/var/log/nginx
        - ./nginx/sites:/etc/nginx/sites-available
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - portainer
        - mariadb
      networks:
        - backend

### MariaDB ##############################################
    mariadb:
      container_name: mariadb
      build: ./mariadb
      volumes:
        - ./data/mariadb:/var/lib/mysql
        - ./data/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "9999:3306"
      environment:
        - MYSQL_DATABASE=ghost
        - MYSQL_USER=ghost
        - MYSQL_PASSWORD=ghost
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - backend
####### Ghost ###################################################
    ghost:
      image: ghost:2.6.1-alpine
      restart: always
      expose:
        - 2368
      volumes:
        - ./data/ghost:/var/lib/ghost
      environment:
        # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
        database__client: mysql
        database__connection__host: mariadb
        database__connection__user: root
        database__connection__password: root
        database__connection__database: ghost
      networks:
        - backend
### phpMyAdmin ###########################################
    phpmyadmin:
      build: ./phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=ghost
        - MYSQL_PASSWORD=ghost
        - MYSQL_ROOT_PASSWORD=root
      expose:
        - 80
      depends_on:
        - mariadb
      networks:
        - backend
### Redis ################################################
    # redis:
    #   container_name: redis
    #   build: ./redis
    #   volumes:
    #     - ${DATA_PATH_HOST}/redis:/data
    #   ports:
    #     - "${REDIS_PORT}:6379"
    #   networks:
    #     - backend
### PHPRedisAdmin ################################################
    # phpredisadmin:
    #   image: erikdubbelboer/phpredisadmin:latest
    #   container_name: phpredisadmin
    #   environment:
    #     - ADMIN_USER=${REDIS_WEBUI_USERNAME}
    #     - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
    #     - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
    #     - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    #   networks:
    #     - backend
    #   ports:
    #     - "${REDIS_WEBUI_PORT}:80"
    #   depends_on:
    #     - redis 
### Cloud9  #################################################
    # cloud9:
    #   container_name: cloud9
    #   build: ./cloud9
    #   stdin_open: true
    #   tty: true
    #   restart: always
    #   command: --auth webide:webide123
    #   ports:
    #     - ${CLOUD_PORT}:8181
    #   networks:
    #     - backend
    #   volumes:
    #      - ${APP_CODE_PATH_HOST}:/workspace
### Portainer ################################################
    portainer:
      container_name: portainer
      image: portainer/portainer
      stdin_open: true
      tty: true
      restart: always
      volumes:
        - ./data/portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9091:9000

### mongo ################################################
    # mongo:
    #   container_name: mongo
    #   build: ./mongo
    #   ports:
    #     - "${MONGODB_PORT}:27017"
    #   volumes:
    #     - ${DATA_PATH_HOST}/mongo:/data/db
    #   networks:
    #     - backend
### MongoWebUI ################################################
    # mongo-webui:
    #   container_name: mongo-webui
    #   build:
    #     context: ./mongo-webui
    #   restart: always
    #   environment:
    #     - ROOT_URL=${MONGO_WEBUI_ROOT_URL}
    #     - MONGO_URL=${MONGO_WEBUI_MONGO_URL}
    #     - INSTALL_MONGO=${MONGO_WEBUI_INSTALL_MONGO}
    #   volumes:
    #     - ${DATA_PATH_HOST}/mongo-webui:/data/db
    #   ports:
    #     - "${MONGO_WEBUI_PORT}:3000"
    #   networks:
    #     - backend
    #   depends_on:
    #     - mongo

